version: "3.2"

services:
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    networks:
      - existing_hadoop_cluster
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    volumes:
      - type: bind
        source: /home/hadoop/docker/volumes/host_shared
        target: /host_shared

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    networks:
      - existing_hadoop_cluster
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    networks:
      - existing_hadoop_cluster
    volumes:
      #- type: volume
      #  source: /home/hadoop/docker/volumes/hive-metastore-postgresql
      #  target: /var/lib/postgresql
      - type: bind
        source: /home/hadoop/docker/volumes/host_shared
        target: /host_shared

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    container_name: presto-coordinator
    networks:
      - existing_hadoop_cluster
    ports:
      - "8080:8080"

networks:
  existing_hadoop_cluster:
    external:
      name: dockersnorlaxserver_default
